### PR TITLE
Add support for Python 3

### LINKED ISSUE #19: Python 3 support
Hello,
I would like to port python-yubico to Python 3, keeping compatibility with Python 2 (preferably 2.6+). Would you be interested in the patches? Anything special I should be aware of?

It seems that most of the work will be breaking circular imports, and figuring out what's text strings and what's bytestrings.

### PR DESCRIPTION
**Pull request by encukou**
Break circular imports, and port to Python 3.

Fixes #19

### CODE REVIEW

**Comment by dainnilsson** [comment]
Thanks! I've skimmed the changes, which look sane at first glance. I plan on looking into this in more detail, as well as doing some testing of it, before merging. I'll keep you updated on any findings!

**Comment by encukou** [comment]
Great! I ran the tests with a borrowed Yubikey v1, so 'll some more testing is definitely in order. I'll be happy to help if any issues arise.

**Comment by dainnilsson** [comment]
Ok, I've run some tests on Python 2.7 and 3.3, and all seems well. A few things before merging:
1). Can you state that you are contributing this code under the license of the project (BSD-2-clause)?
2). I see that the scripts in util as well as examples have not been updated to be compatible with Python 3. This is probably something we would want as well. Would you be willing to contribute those changes as well? If not, then I'm sure we can get someone here to take a stab at it, it probably doesn't require very much effort.

**Comment by encukou** [comment]
1) Yes, I am contributing the changes under the project's licence.
It's mostly shuffling code around, so it might not be copyrightable. In case it is, it's `© Red Hat, Inc. and/or its affiliates`, who are happy to release my contributions under the BSD. I am not a lawyer; I you need one to confirm all this, let me know.

2) Ah, I knew I forgot something! I ported it in commit 02c2ff4bc7fab92245fb05be1ba105f1a6e8cc80, but I won't have access to a Yubikey until Tuesday. If you have time until then, feel free to pull it if it works or fix if it doesn't.

**Comment by dainnilsson** [comment]
Thanks! Not to sound too demanding, but I think you missed the files in examples/. Unfortunately I'm heading off on vacation in a few hours, and I'm not going to have time to look at the new commits. To avoid having the whole PR stall while I'm away for 4 weeks, I'm going to go ahead and merge it now, without util/ and examples/. I'd be happy to look at a new pull request for those files once I'm back, unless someone else already does do in the meantime.

**Comment by encukou** [comment]
Thanks!

I've ordered my own Yubikey and will test & push the remaining work soon as it arrives :)

**Comment by encukou** [comment]
The follow-up is at #24.

**Pull request merged**
